version: 0.2

env:
  variables:
    $REPOSITORY_URL: 891377157603.dkr.ecr.us-east-1.amazonaws.com/aws-spring-boot
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging into ECR Start
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377157603.dkr.ecr.us-east-1.amazonaws.com
      - echo Setting repo URL
      - echo Setting image tag
      - printenv
  build:
    commands:
      - echo Building the image
      - ./gradlew clean build
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the image
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - export IMAGE_NAME='aws-spring-boot'
      - export IMAGE_URI=$REPOSITORY_URL:$IMAGE_TAG
      - "printf '[{\"name\":\"%s\",\"imageUri\":\"%s\"}]' \"$IMAGE_NAME\" \"$IMAGE_URI\" > imagedefinitions.json"
artifacts:
  files:
    - imagedefinitions.json